use crate::protocol::message::ServerMessage;
use execution_queue::types::ExecutionStatus;
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc::Sender;
use uuid::Uuid;

pub type UserId = Uuid;

pub type CellId = Uuid;

/// Client-generated request id
pub type RequestId = Uuid;

/// Context sent with certain (cell-level) operations to encapsulate clients current state
#[derive(Debug, Clone, Deserialize)]
pub struct NotebookOperationContext {
    /// Client-generated request id used for optimistic updates
    pub request_id: RequestId,
}

/// Server context sent with some operation's broadcasts to allow clients to correctly update their state
#[derive(Debug, Clone, Serialize)]
pub struct NotebookStateUpdateContext {
    /// User who requested the operation
    pub user_id: UserId,

    /// Request id generated by the client, links this update to a particular operation request
    pub request_id: RequestId,
}

/// Context sent with certain text operations to encapsulate clients current state
#[derive(Debug, Clone, Deserialize)]
pub struct TextOperationContext {
    /// Cell content version to which the operation was issued
    pub base_cell_version: u64,

    pub request_id: RequestId,
}

#[derive(Debug, Clone, Serialize)]
pub struct TextStateUpdateContext {
    /// Current version of the cell content after the operation
    pub cell_version: u64,

    /// User who requested the operation
    pub user_id: UserId,

    /// Request id generated by the client, links this update to a particular operation request
    pub request_id: RequestId,
}

#[derive(Debug, Clone, Serialize)]
pub struct User {
    pub id: UserId,
    pub name: Option<String>,
    pub focused_cell: Option<CellId>,
    pub cursor_position: Option<usize>,
    #[serde(skip_serializing)]
    pub tx_channel: Sender<ServerMessage>,
}

impl User {
    pub fn new(tx_channel: Sender<ServerMessage>) -> Self {
        Self {
            id: UserId::new_v4(),
            name: None,
            focused_cell: None,
            cursor_position: None,
            tx_channel,
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct Execution {
    pub cell_id: CellId,
    pub user_id: UserId,
    pub status: ExecutionStatus,
}
