[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

axum = { version = "0.8.8", features = ["ws"] }
tower-http = { version = "0.6.8", features = ["cors"] }
futures = "0.3"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

notebook = { path = "../notebook" }
execution_queue = { path = "../execution_queue" }
ot = { path = "../ot" }
